### ISSUE TITLE
Galaxyline config

### ISSUE THREAD

**Issue by MatthiasGrandl** [yamatsum/nvim-nonicons#11]
Could you please share the Galaxyline config from the screenshot? Love how minimal it is. Thanks for the cool icon set!

**Comment by vinodnimbalkar** [comment]
@MatthiasGrandl Please check out these galaxyline configuration. https://github.com/vinodnimbalkar/dotfiles/blob/master/.config/nvim/lua/statusline.lua
It is combination of @yamatsum and my configuration. BTW @yamatsum Thanks for the very cool icons.

**Comment by MatthiasGrandl** [comment]
@vinodnimbalkar worked great thanks! but I had to switch the unicode icons as they didn't match the nonicons in my case for some reason.
