### ISSUE TITLE
Icons appear as question mark

### ISSUE THREAD

**Issue by MustafaErgul** [yamatsum/nvim-nonicons#18]
I have installed https://github.com/yamatsum/nonicons/issues and chosen from iterm2 preferences already. Somehow icons don't appear on the nvim-tree plugin. 

I am not using packer to download plugins, not sure if I should :/

`:lua print(require('nvim-nonicons').get('light-bulb'))` also works as expected.

Here are some screenshots;

![image](https://user-images.githubusercontent.com/5095547/138262186-da9823ec-7679-4c2c-99ec-09af0b7953c6.png)
![image](https://user-images.githubusercontent.com/5095547/138262242-72dce8d1-0940-492c-b634-e699201815b6.png)
![image](https://user-images.githubusercontent.com/5095547/138262306-f70db0f6-ddc2-4a5a-9274-e9f98d5022eb.png)

Thanks.

**Comment by yamatsum** [comment]
If you are using nvim-tree, try the following settings.
```
local icons = require "nvim-nonicons"

vim.g.nvim_tree_icons = {
  default = icons.get("file"),
  folder = {
    default = icons.get("file-directory"),
    open = icons.get("file-directory-outline"),
    symlink = icons.get("file-directory"),
    symlink_open = icons.get("file-directory-outline"),
    empty = icons.get("file-directory-outline"),
    empty_open = icons.get("file-directory-outline"),
    arrow_open = icons.get("chevron-down"),
    arrow_closed = icons.get("chevron-right")
  }
}

```

**Comment by MustafaErgul** [comment]
Thanks for your suggestion, I will try this out. Since I have switched to `nvim-dev-icons` I am not able to test this yet. However thanks for your time ❤️

**Comment by lougreenwood** [comment]
@yamatsum I also hit this issue and your suggestion fixed the problem - thanks, this iconset looks great, nice to finally have icons which are a decent size! 🙏
