### ISSUE TITLE
completion and statusline config

### ISSUE THREAD

**Issue by p00f** [yamatsum/nvim-nonicons#3]
Can you share your completion and statusline configuration? Some of the icons aren't there in mapping.lua

**Comment by yamatsum** [comment]
this is my setting. I hope it helps
https://github.com/yamatsum/mackup/blob/master/.config/nvim/lua/plugin/completion-nvim.lua
https://github.com/yamatsum/mackup/blob/master/.config/nvim/lua/plugin/galaxyline.lua

> Some of the icons aren't there in mapping.lua
Which icon is it?

**Comment by p00f** [comment]
operator, function etc (which you've used similar-looking icons for in your config). Thanks!

**Comment by p00f** [comment]
Can you also show which icons you've used for statusline diagnostics?

**Comment by yamatsum** [comment]
I use "package" icon at function. ("diff" is also at operator)
https://octicons-primer.vercel.app/octicons/

**Comment by yamatsum** [comment]
I tried using "check", "alert", "stop" for diagnostics

**Comment by p00f** [comment]
Thanks!
