### ISSUE TITLE
Add elixir icon

### ISSUE THREAD

**Issue by skbolton** [yamatsum/nvim-nonicons#4]
Looks like this would need to be added to the font. Created an issued [here](https://github.com/yamatsum/nonicons/issues/5#issue-833202564) for the font repo

Elixir files end in a `.ex` or `.exs`

**Comment by yamatsum** [comment]
How about using "beaker" as a workaround?
https://octicons-primer.vercel.app/octicons/beaker-16

**Comment by skbolton** [comment]
I'd rather have the web-devicons version than a beaker personally.

**Comment by yamatsum** [comment]
@skbolton how about this?
<img width="113" alt="Screen Shot 2021-03-30 at 14 04 20" src="https://user-images.githubusercontent.com/42740055/112936606-17acfc00-9161-11eb-92f8-eb33d631cf67.png">

**Comment by skbolton** [comment]
Nice! I do wonder how it would look to have some of the original character of the elixir logo. Just a subtle tilt to the top tip 
![image](https://user-images.githubusercontent.com/13260877/113074037-8604b500-9187-11eb-9c9a-4456243b4928.png)

**Comment by yamatsum** [comment]
All icons are not the same as the original ones.
Abstracted to increase literacy rate

**Comment by skbolton** [comment]
Looks like this icon was added.
